### ISSUE TITLE
Sample site to review?

### ISSUE THREAD

**Issue by vielmetti** [bclswl0827/webrx4mobile#1]
Is there a site running this software we can test and provide feedback for? Very interested in reviewing this, and in seeing how it works.

**Comment by bclswl0827** [comment]
https://s.ibcl.us/webview/m.wrx
Here is an example :)

**Comment by vielmetti** [comment]
Thanks!

When I try to connect to that site with Firefox / Windows 10, I get this error:

`s.ibcl.us has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.`

**Comment by bclswl0827** [comment]
I use CloudFlare CDN, you get this error indicating that your traffic may be hijacked.

> Thanks!
> 
> When I try to connect to that site with Firefox / Windows 10, I get this error:
> 
> `s.ibcl.us has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.`

**Comment by bclswl0827** [comment]
![20190820212143](https://user-images.githubusercontent.com/24319042/63350715-870d1800-c390-11e9-9f08-31b27c5a4db1.png)
Here is a screenshot of this demo

**Comment by vielmetti** [comment]
Got it running. How do you jump to a specific frequency?

**Comment by bclswl0827** [comment]
> Got it running. How do you jump to a specific frequency?

First click the signal in the waterfall, then fine-tune by using the buttons below the frequency.
At the moment, there are still some troubles, and I may improve later.
I am a student, I don't have much time to deal with it, sorry (
